### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (4,) (3,)

### ISSUE THREAD

**Issue by jstitlow** [tlambert03/napari-omero#8]
I am very excited to see napari and omero working together!!

Installation and login were flawless but I am not able to open images through the command line, e.g. `napari Image:123456`. 

<details>
  <summary>Here is the full traceback for the ValueError</summary>
  
Traceback (most recent call last):
  File "/opt/anaconda3/envs/omero/bin/napari", line 8, in <module>
    sys.exit(main())
  File "/opt/anaconda3/envs/omero/lib/python3.7/site-packages/napari/__main__.py", line 171, in main
    **kwargs,
  File "/opt/anaconda3/envs/omero/lib/python3.7/site-packages/napari/view_layers.py", line 208, in view_path
    path=path, stack=stack, plugin=plugin, layer_type=layer_type, **kwargs
  File "/opt/anaconda3/envs/omero/lib/python3.7/site-packages/napari/components/add_layers_mixin.py", line 859, in open
    _path, kwargs, plugin=plugin, layer_type=layer_type
  File "/opt/anaconda3/envs/omero/lib/python3.7/site-packages/napari/components/add_layers_mixin.py", line 925, in _add_layers_with_plugins
    new = self._add_layer_from_data(*_data)
  File "/opt/anaconda3/envs/omero/lib/python3.7/site-packages/napari/components/add_layers_mixin.py", line 997, in _add_layer_from_data
    layer = add_method(data, **(meta or {}))
  File "/opt/anaconda3/envs/omero/lib/python3.7/site-packages/napari/components/add_layers_mixin.py", line 230, in add_image
    return self.add_layer(layers.Image(data, **kwargs))
  File "/opt/anaconda3/envs/omero/lib/python3.7/site-packages/napari/layers/image/image.py", line 246, in __init__
    self._update_dims()
  File "/opt/anaconda3/envs/omero/lib/python3.7/site-packages/napari/layers/base/base.py", line 403, in _update_dims
    self.refresh()
  File "/opt/anaconda3/envs/omero/lib/python3.7/site-packages/napari/layers/base/base.py", line 636, in refresh
    self._update_coordinates()
  File "/opt/anaconda3/envs/omero/lib/python3.7/site-packages/napari/layers/base/base.py", line 648, in _update_coordinates
    self.status = self.get_message()
  File "/opt/anaconda3/envs/omero/lib/python3.7/site-packages/napari/layers/base/base.py", line 711, in get_message
    coordinates = self._transforms.simplified(self.coordinates)
  File "/opt/anaconda3/envs/omero/lib/python3.7/site-packages/napari/layers/transforms.py", line 103, in simplified
    return tz.pipe(self[0], *[tf.compose for tf in self[1:]])
  File "/opt/anaconda3/envs/omero/lib/python3.7/site-packages/toolz/functoolz.py", line 634, in pipe
    data = func(data)
  File "/opt/anaconda3/envs/omero/lib/python3.7/site-packages/napari/layers/transforms.py", line 182, in compose
    scale = self.scale * transform.scale
ValueError: operands could not be broadcast together with shapes (4,) (3,)
</details>

The error occurs: 
* after establishing a session through the GUI (`napari_omero`), presumably the session info is saved. 
* regardless of image dimensions (3D, 4D, single channel and multi channels)

**Comment by will-moore** [comment]
Hi Josh,
 I think that should be fixed by https://github.com/tlambert03/napari-omero/pull/7

If that's the case, then single-Z images should work?
Also Z-stack images with single-C AND single-T should open? Or with multi-C AND multi-T?
Cheers,
  Will

**Comment by tlambert03** [comment]
i just merged #7 into master.  @jstitlow can you give it a try and see if it fixes?  If you cloned the repo, just pull the recent master, if you installed from pip, you should be able to update with `pip install git+git://github.com/tlambert03/napari-omero.git`

**Comment by jstitlow** [comment]
Thanks guys. 

That solves the problem.

**Comment by tlambert03** [comment]
thanks for letting us know!
